services:
  # === Combined App (React + Spring Boot) ===
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: combined-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - KEYCLOAK_REDIRECT_URI=${KEYCLOAK_REDIRECT_URI}
      - KEYCLOAK_AUTH_URI=${KEYCLOAK_AUTH_URI}
      - KEYCLOAK_TOKEN_URI=${KEYCLOAK_TOKEN_URI}
      - KEYCLOAK_JWK_URI=${KEYCLOAK_JWK_URI}
    depends_on:
      opensearch-node1:
        condition: service_started
      keycloak:
        condition: service_healthy
    networks:
      - opensearch-net

  # === Nginx Reverse Proxy ===
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      app:
        condition: service_started
    networks:
      - opensearch-net

  # === Keycloak Authentication Server ===
  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak-db:5432/keycloak
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - KC_HTTP_ENABLED=true
      - KC_FRONTEND_URL=http://localhost

    command: start-dev
    depends_on:
      keycloak-db:
        condition: service_started
    healthcheck:
      test: ["CMD", "/opt/keycloak/bin/kc.sh", "show-config"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s
    networks:
      - opensearch-net

  # === Keycloak Database ===
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    environment:
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=keycloak123
      - POSTGRES_DB=keycloak
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    networks:
      - opensearch-net

  # === OpenSearch ===
  opensearch-node1:
    image: opensearchproject/opensearch:3
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_cluster_manager_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
      - "DISABLE_SECURITY_PLUGIN=true"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    expose:
      - "9200"
    networks:
      - opensearch-net

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    expose:
      - "5601"
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
      - "SERVER_BASEPATH=/opensearch"
      - "SERVER_REWRITEBASEPATH=true"
    depends_on:
      opensearch-node1:
        condition: service_started
    networks:
      - opensearch-net

volumes:
  opensearch-data1:
  keycloak_db_data:

networks:
  opensearch-net: